#!/bin/sh

REL_NAME=erl
REL_VSN=@REL_VSN@
ERTS_VSN=@ERTS_VSN@

PREFIX=$(cd $(dirname $(dirname $0)); pwd)

# Backwards compatibility pathing
if [ -d "$PREFIX/packages" ]; then
    export ROOTDIR="$PREFIX/packages/$ERTS_VSN"
    export BINDIR="$ROOTDIR/erts-$ERTS_VSN/bin"
    export LD_LIBRARY_PATH="$ROOTDIR/erts-$ERTS_VSN/lib:$LD_LIBRARY_PATH"
else
    export ROOTDIR="$PREFIX/application_packages/$ERTS_VSN"
    export BINDIR="$PREFIX/erts_packages/erts-$ERTS_VSN/bin"
    export LD_LIBRARY_PATH="$PREFIX/erts_packages/erts-$ERTS_VSN/lib:$LD_LIBRARY_PATH"
fi

export EMU=beam
export PROGNAME=erl

REL_DIR=$PREFIX/release_packages/$REL_NAME-$REL_VSN/release

exec $BINDIR/erlexec -boot $REL_DIR/$REL_NAME -noshell -run escript start -extra ${1+"$@"}
