#!/bin/sh

cd $(dirname $0)

if [ "$#" != "2" ];then
	echo ""
	echo "usage: $0 <appname> <prefix>"
	echo ""
	echo "appname is the title of the application to be generated"
	echo "prefix is the prefix that will be appended to all files in"
	echo "the application due to erlangs lack of a package structure.  The prefix"
	echo "is typicaly the first letter of each word in the name of the application"
	echo ""
	echo "example: $0 chat_server cs"
	echo ""
	exit 1
fi

APP_NAME=$1
APP_NAME_UPPER_CASE=$(echo $APP_NAME | tr a-z A-Z)
PREFIX=$2

if [ -e ../lib/$APP_NAME ];then
	echo "an application with name $APP_NAME already exists would you like to delete it [y|N] $> \c"
	read DEL
	if [ "$DEL" != "y" ];then
		echo "aborting application creation"
		exit 1
	fi
	echo "deleting $APP_NAME"
	rm -rf ../lib/$APP_NAME
fi


cd .appgen
echo `pwd`

cp -r blank_app $APP_NAME

cd $APP_NAME/src
ls blank_app* | ../../rename.sh blank_app $APP_NAME
cd -

# The base directory of the application
./substitute.sh %%APP_NAME_UPPER_CASE%% $APP_NAME_UPPER_CASE $APP_NAME/Makefile
./substitute.sh %%APP_NAME_UPPER_CASE%% $APP_NAME_UPPER_CASE $APP_NAME/vsn.mk

# The src directory of the application
./substitute.sh %%APP_NAME%% $APP_NAME $APP_NAME/src/Makefile
./substitute.sh %%APP_NAME_UPPER_CASE%% $APP_NAME_UPPER_CASE $APP_NAME/src/Makefile
./substitute.sh %%PFX%% $PREFIX $APP_NAME/src/Makefile

# include directory
mv $APP_NAME/include/blank_app.hrl $APP_NAME/include/"$APP_NAME".hrl

mv $APP_NAME ../../lib

echo ""
echo "$APP_NAME has been generated and placed under lib/$APP_NAME"
echo ""
